### PR TITLE
Website: make it work without JS

### PR DESCRIPTION
**Pull request by srid**
Uses https://github.com/srid/emanote/pull/225

cf. https://github.com/Plutonomicon/plutonomicon/pull/21#issuecomment-1008148774

### CODE REVIEW

**Comment by L-as** [comment]
Thanks! I wonder how/when the pages are regenerated.

**Comment by srid** [comment]
For some reason the CI is not running for this merge: https://github.com/Plutonomicon/plutonomicon/commit/854eccefce4b66b78aa8aa76a7e79bca86b44d44

@MatthewCroughan - is this because the agent is down?

EDIT: n/m - it ran eventually.

**Comment by srid** [comment]
Pages should be regenerated and deployed in Hercules CI (`main` branch only). @L-as

**Comment by MatthewCroughan** [comment]
@srid If this effect ran on any branch, that means any PR would update the production website. That is not what we want. The only solution is to have multiple repos and mulitple domains. Github does not support staging domains for gh-pages based on multiple branches.

**Comment by MatthewCroughan** [comment]
To clarify, think about it, if you make a PR do you really want that PR to effect the main website? What you want is a staging server, but that is not supported by GH Pages. GH Pages only supports a single website, not subdomains per branch.

**Comment by L-as** [comment]
You could have a subdirectory on the website, such that e.g. `https://plutonomicon.github.io/plutonomicon//staging` uses the staging branch.

**Comment by srid** [comment]
> You could have a subdirectory on the website, such that e.g. `https://plutonomicon.github.io/plutonomicon//staging` uses the staging branch.

I hadn't thought of this, but having per-branch deployment (let's call it **deploy previews**) would indeed actually be useful towards this end: 

- someone opens a PR changing the docs,
- their PR gets an unique web URL (based on branch name) of their branch deployed 
- others can take a look at the rendered site, as part of PR review. 

(Not sure if this will work for fork's branches.)

Example of it in action, using a deploy service called Netlify: https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

Cloudflare Pages also supports it, in someway (not sure if they have PR integration): https://developers.cloudflare.com/pages/platform/preview-deployments

GitHub Pages team is planning to support deploy preview in the medium term: https://github.com/github/feedback/discussions/7730#discussioncomment-1885967 - but that might require the use of GitHub Actions.

**Comment by MatthewCroughan** [comment]
If we have to make compromises to our Hercules-CI usage and therefore Nix usage to use Github Pages deploy preview, I think it's worth hosting our own webserver(s). Serving static HTML files is not a hard thing to do, then we have full control over what happens in DNS, etc.

**Comment by MatthewCroughan** [comment]
Additionally, Hercules-CI will support fork PRs at some point soon. Right now @roberth is working on Hercules 0.9, which includes more fine grained controls over what happens with agent secrets. Stuff like this is necessary for security, otherwise forked PRs could use our secrets, which isn't sensible.

**Pull request merged**
